image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 5005
    onOpen: ignore
  - port: 9990
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 5432
    onOpen: ignore

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true

vscode:
  extensions:
    - redhat.mta-vscode-extension@0.0.79

tasks:
  - name: Pre-warm Maven
    init: mvn -fn dependency:resolve-plugins dependency:resolve dependency:go-offline clean compile package
  - name: Start PostgreSQL container
    command: docker run -d -p 5432:5432 -e POSTGRES_USER=coolstore -e POSTGRES_PASSWORD=coolstore123 -e POSTGRES_HOST_AUTH_METHOD=md5 -e POSTGRES_DB=monolith postgres
  - name: Start Wildfly server
    command: mkdir -p /workspace/deployments && $JBOSS_HOME/bin/standalone.sh -b 0.0.0.0
