image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 5005
    onOpen: ignore
  - port: 9990
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-maven
    - vscjava.vscode-java-test
    - redhat.mta-vscode-extension

tasks:
  # - before: sdk install java 17.0.12-tem < /dev/null
  - name: Pre-warm Maven
    init: mvn -fn dependency:resolve-plugins dependency:resolve dependency:go-offline clean compile package
  - name: Start PostgreSQL container
    command: docker run -d -p 5432:5432 -e POSTGRES_USER=coolstore -e POSTGRES_PASSWORD=coolstore123 -e POSTGRES_HOST_AUTH_METHOD=md5 -e POSTGRES_DB=monolith postgres
  - name: Setup Wildfly server
    command: mkdir -p /workspace/deployments && $JBOSS_HOME/bin/jboss-cli.sh --echo-command --file=/workspace/workshop-migrate-jboss-on-app-service/setup/config.cli && rm -rf $JBOSS_HOME/standalone/configuration/standalone_xml_history
  - name: Start Wildfly server
    command: $JBOSS_HOME/bin/standalone.sh -b 0.0.0.0
